LOAD DATA LOCAL INFILE "article.txt" INTO TABLE Article
  FIELDS TERMINATED BY "," ENCLOSED BY '"'
  LINES TERMINATED BY "\n";

LOAD DATA LOCAL INFILE "field.txt" INTO TABLE Field
  FIELDS TERMINATED BY "," 
  ENCLOSED BY '"'
  LINES TERMINATED BY "\n";

LOAD DATA LOCAL INFILE "has_experience.txt" INTO TABLE Has_Experience
  FIELDS TERMINATED BY "," ENCLOSED BY '"'
  LINES TERMINATED BY "\n";

LOAD DATA LOCAL INFILE "user.txt" INTO TABLE User
  FIELDS TERMINATED BY "," ENCLOSED BY '"'
  LINES TERMINATED BY "\n";

  LOAD DATA LOCAL INFILE "admin.txt" INTO TABLE Admin
  FIELDS TERMINATED BY "," ENCLOSED BY '"'
  LINES TERMINATED BY "\n";